# Generated by Django 3.1.5 on 2021-08-01 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribucion_Puertos_a_Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Puerto', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Olt',
            fields=[
                ('MAC_OLT', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('Modelo', models.CharField(max_length=50)),
                ('Detalle', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=50)),
                ('Capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Contratado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Velocidad', models.IntegerField()),
                ('Detalle', models.CharField(max_length=50)),
                ('tabla_trafico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Red_Alimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_FO', models.CharField(max_length=10, unique=True)),
                ('Detalle_recorrido', models.CharField(max_length=50)),
                ('Capacidad', models.IntegerField()),
                ('Marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Numero', models.IntegerField()),
                ('Detalle', models.CharField(max_length=50)),
                ('Gemport', models.CharField(max_length=4)),
                ('ServicePort', models.CharField(max_length=4)),
                ('LineProfile', models.CharField(max_length=4)),
                ('UserVlan', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaOLT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Tarjeta', models.IntegerField(unique=True)),
                ('Capacidad', models.IntegerField()),
                ('Olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olts', to='gestion.olt')),
            ],
        ),
        migrations.CreateModel(
            name='Red_Distribucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_FO', models.CharField(max_length=20, unique=True)),
                ('Detalle_recorrido', models.CharField(max_length=50)),
                ('Capacidad', models.CharField(max_length=30)),
                ('Marca', models.CharField(max_length=30)),
                ('Distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='NAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=10, unique=True)),
                ('Hilo', models.CharField(max_length=10)),
                ('Tubillo', models.CharField(max_length=10)),
                ('Capacidad', models.IntegerField()),
                ('Ubicacion', models.CharField(max_length=60)),
                ('FO_Distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribucion', to='gestion.red_distribucion')),
                ('Spliiter_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.distribucion_puertos_a_distrito')),
            ],
        ),
        migrations.CreateModel(
            name='IP_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('Vlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ips', to='gestion.vlan')),
            ],
            options={
                'ordering': ('ip',),
            },
        ),
        migrations.CreateModel(
            name='Hilos_Alimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tubillo', models.CharField(max_length=20)),
                ('Color_hilo', models.CharField(max_length=20)),
                ('FO_Alimentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacion', to='gestion.red_alimentacion')),
            ],
        ),
        migrations.AddField(
            model_name='distribucion_puertos_a_distrito',
            name='Distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.distrito'),
        ),
        migrations.AddField(
            model_name='distribucion_puertos_a_distrito',
            name='ID_Fibra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.hilos_alimentacion'),
        ),
        migrations.AddField(
            model_name='distribucion_puertos_a_distrito',
            name='Tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tarjetaolt'),
        ),
        migrations.AddField(
            model_name='distribucion_puertos_a_distrito',
            name='VLAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.vlan'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=60)),
                ('Sn_auth', models.CharField(max_length=50, unique=True)),
                ('Numero_ont', models.IntegerField(unique=True)),
                ('Numero_ServicePort', models.IntegerField(unique=True)),
                ('Actualizar_Script', models.BooleanField(default=True)),
                ('Script', models.TextField(editable=False, null=True)),
                ('Distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.distrito')),
                ('IP', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='gestion.ip_address')),
                ('Nap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='gestion.nap')),
                ('Plan_Contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.plan_contratado')),
            ],
        ),
    ]
