# Generated by Django 3.1.5 on 2021-08-24 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20210824_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucion_puertos_a_distrito',
            name='ID_Fibra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='gestion.hilos_alimentacion', unique=True),
        ),
    ]
