# Generated by Django 3.1.5 on 2021-08-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20210824_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nap',
            name='Spliiter_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.distribucion_puertos_a_distrito'),
        ),
    ]
