# Generated by Django 3.1.5 on 2021-08-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20210824_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='red_distribucion',
            name='Capacidad',
            field=models.IntegerField(),
        ),
    ]
